// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tickets.Data;

#nullable disable

namespace Tickets.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("Tickets.Models.Bus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Capacity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Buses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capacity = 18,
                            Model = "Mercedes-Benz Sprinter",
                            Number = "AP 1234 BT"
                        },
                        new
                        {
                            Id = 2,
                            Capacity = 25,
                            Model = "Setra S 515 HD",
                            Number = "AA 7777 XX"
                        });
                });

            modelBuilder.Entity("Tickets.Models.Route", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BusId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DepartureTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("From")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Price")
                        .HasColumnType("INTEGER");

                    b.Property<string>("To")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BusId");

                    b.ToTable("Routes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BusId = 1,
                            DepartureTime = new DateTime(2026, 5, 10, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            From = "Zaporozhye",
                            Price = 850,
                            To = "Kyiv"
                        },
                        new
                        {
                            Id = 2,
                            BusId = 2,
                            DepartureTime = new DateTime(2026, 5, 11, 14, 30, 0, 0, DateTimeKind.Unspecified),
                            From = "Kyiv",
                            Price = 600,
                            To = "Lviv"
                        },
                        new
                        {
                            Id = 3,
                            BusId = 2,
                            DepartureTime = new DateTime(2026, 5, 21, 12, 30, 0, 0, DateTimeKind.Unspecified),
                            From = "Kyiv",
                            Price = 800,
                            To = "Zaporozhye"
                        },
                        new
                        {
                            Id = 4,
                            BusId = 1,
                            DepartureTime = new DateTime(2026, 5, 21, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            From = "Zaporozhye",
                            Price = 1300,
                            To = "Lviv"
                        });
                });

            modelBuilder.Entity("Tickets.Models.Ticket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("PurchaseDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("RouteId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RouteId");

                    b.HasIndex("UserId");

                    b.ToTable("Tickets");
                });

            modelBuilder.Entity("Tickets.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "admin@tickets.com",
                            LastName = "System",
                            Name = "Admin",
                            Password = "admin_password",
                            Role = 1
                        },
                        new
                        {
                            Id = 2,
                            Email = "User@mail.com",
                            LastName = "User",
                            Name = "User",
                            Password = "user_password",
                            Role = 0
                        });
                });

            modelBuilder.Entity("Tickets.Models.Route", b =>
                {
                    b.HasOne("Tickets.Models.Bus", "Bus")
                        .WithMany("Routes")
                        .HasForeignKey("BusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bus");
                });

            modelBuilder.Entity("Tickets.Models.Ticket", b =>
                {
                    b.HasOne("Tickets.Models.Route", "Route")
                        .WithMany("Tickets")
                        .HasForeignKey("RouteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Tickets.Models.User", "User")
                        .WithMany("Tickets")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Route");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Tickets.Models.Bus", b =>
                {
                    b.Navigation("Routes");
                });

            modelBuilder.Entity("Tickets.Models.Route", b =>
                {
                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("Tickets.Models.User", b =>
                {
                    b.Navigation("Tickets");
                });
#pragma warning restore 612, 618
        }
    }
}
